### ISSUE TITLE
Indoor and outdoor real-world datasets 

### ISSUE THREAD

**Issue by ConanMusk** [JiayongO-O/PENonLocal#2]
我没能找到data_gener\TestData此文件下面的数据集，麻烦能告诉一下吗

**Comment by ConanMusk** [comment]
![2021-08-24 16-48-45屏幕截图](https://user-images.githubusercontent.com/67884112/130587813-91e1d0d3-7c1c-4a3e-bede-e02132876f96.png)
这个参数对应的路径好像不存在

**Comment by JiayongO-O** [comment]
Hi @ConanMusk , you should first generate the test data with "SimulateTestMeasurements.m" in data_gener/TestData/middlebury. After that you would found the files in that folder. And DO NOT forget to download the raw data by executing `bash ./data_gener/TrainData/download_nyu_dataset.bash`.

The path "./preTrain/" means that when you test a network, you can get your trained model from this path (after you put it there).

Thanks.

**Comment by ConanMusk** [comment]
感谢。
![2021-08-24 21-41-25屏幕截图](https://user-images.githubusercontent.com/67884112/130627819-35afd77c-1dd9-4896-a986-7953cd302f3b.png)
![2021-08-24 21-42-56屏幕截图](https://user-images.githubusercontent.com/67884112/130628035-abfef8d6-9bf8-420f-99b4-1d375e90e6ec.png)
这么多吗，我是出错了吗？

**Comment by ConanMusk** [comment]
SPAD维度是（1，1024，64，64），它每一维度对应的含义是什么，之前的问题解决了

**Comment by ConanMusk** [comment]
![image](https://user-images.githubusercontent.com/67884112/135734382-8a35d67f-3a51-4ece-ab2a-aabeb79f5ed4.png)
这有问题吗？感觉不对

**Comment by ConanMusk** [comment]
感觉效果很差

**Comment by ConanMusk** [comment]
训练时间也并不是文中说的35小时
