### ISSUE TITLE
Why you use the bin?

### ISSUE THREAD

**Issue by ConanMusk** [JiayongO-O/PENonLocal#3]
![图片](https://user-images.githubusercontent.com/67884112/149865387-fdf656ac-2d46-4005-be4b-b69b314cd3c7.png)

这个bin里面的不是不好的信息吗？为什么你之后计算的时候是用bin数据来对比
![图片](https://user-images.githubusercontent.com/67884112/149865543-da4f4a95-6cd3-44a0-9a3d-f6bda97c3c2f.png)
![图片](https://user-images.githubusercontent.com/67884112/149865616-de492b3f-5c54-4703-b2e3-d68161d7a616.png)

**Comment by JiayongO-O** [comment]
Hi, the "bin" is the 2D ground-truth depth map, which you can find in simulation named "range_bins". Well, it from the NYU2 dataset and will contain some artifacts, so that we do some pre-processing to refine it, e.g., replacing the outliers. Thanks.

**Comment by ConanMusk** [comment]
![图片](https://user-images.githubusercontent.com/67884112/149868211-57679925-fb7e-4313-b42e-c4298e8d1aab.png)
bin的深度信息不太好，这里计算rmse的时候为什么用bin数据
![图片](https://user-images.githubusercontent.com/67884112/149868417-63137468-222a-4b23-8dfa-a51026d85bbc.png)

**Comment by ConanMusk** [comment]
Look forward to your  reply.

**Comment by JiayongO-O** [comment]
Note that, bin is the **GROUND-TRUTH** depth map, which we are targeting on. Of cause we should compute rmse with it! What do you mean with "深度信息不太好"? It is from the NYU2 dataset. What kind of depth information is GOOD in your opinion? Why do you care about the **GROUND-TRUTH** depth map???

**Comment by ConanMusk** [comment]
![图片](https://user-images.githubusercontent.com/67884112/149879630-c3474b33-a775-4da6-9d3e-5ca7917275dd.png)
Oh sorry, I thought the one on the left was GT and the one on the right was the noise depth map extracted from SPAD.

**Comment by ConanMusk** [comment]
I will continue to study your code and articles.
