### ISSUE TITLE
Compiling Mex for ConvertRGBD

### ISSUE THREAD

**Issue by felipegb94** [JiayongO-O/PENonLocal#4]
Hi Jiayong,

I am having trouble compiling the `intrinsic_textures` library that is used in the `ConvertRGBD.m`. I think my issue is that the library uses an old OpenCV version.

What versions of `opencv` and `libann` do you use?

Thanks,
Felipe

**Comment by JiayongO-O** [comment]
Hi Felipe,

sorroy for the late. It has been a long time after generating the data. I remmeber the opencv=3.4.7, libann=1.1.2, on Ubuntu 16.04. Maybe higher versions are OK. Hope it helps. 

Thanks,
Jiayong

**Comment by felipegb94** [comment]
Thanks for the response Jiayong!

I finally got it to compile on Ubuntu 20.04 and using MATLAB 2021b. I used OpenCV `3.4.13` (which I had to compile from source) and also `libann=1.1.2`. 

I also had to change the `compile.m` script to:

```
mex -I/usr/include/ANN -L/usr/lib/ -lann -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_core getConstraintsMatrix.cpp mexBase.cpp
mex -I/usr/include/ANN -L/usr/lib/ -lann -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_core getContinuousConstraintMatrix.cpp mexBase.cpp 
mex -I/usr/include/ANN -L/usr/lib/ -lann -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_core getGridLLEMatrix.cpp mexBase.cpp LLE.cpp 
mex -I/usr/include/ANN -L/usr/lib/ -lann -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_core getGridLLEMatrixNormal.cpp mexBase.cpp LLE.cpp
mex -I/usr/include/ANN -L/usr/lib/ -lann -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_core getNormalConstraintMatrix.cpp mexBase.cpp
```

After this I still got a runtime error of `invalid Mex file`, because `version "GLIBCXX_3.4.26" not found (required by /usr/local/lib/libopencv_core.so.3.4)`. So I forced MATLAB to use my system's `libstdc++.so.6`, by setting the following environment variable:

```
export LD_PRELOAD=$LD_PRELOAD:"/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
```

Thanks,
Felipe
