### ISSUE TITLE
ConvertRGBD.m crashes MATLAB with some scenes

### ISSUE THREAD

**Issue by felipegb94** [JiayongO-O/PENonLocal#5]
Hi,
I was wondering if you experienced the following issue when running `ConvertRGBD.m`. 
When processing some files such as `living_room_0059_0195`, `living_room_0059_0204`, `living_room_0059_0208`, MATLAB crashes possibly due to a segmentation fault in the Mex files.
Did you encounter this issue when generating the dataset?
Thanks,
Felipe

**Comment by JiayongO-O** [comment]
Hi Felipe,

I haven't encountered crashes for matlab when processing such scenes. I think it is correlated with the mex files. Ubuntu is not very friendly with mex files and sometimes the GCC version will also influence the complie, in my experience. Hope it helps. 

Thanks,
Jiayong

**Comment by felipegb94** [comment]
Thanks for your response Jiayong!

Yeah I looked into it further and in MATLAB 2021b, I have encountered two errors that make the program crash:

1. On a few images (~10 of them) the `imread` function is not able to read the RGB `.ppm` file. But I think this is a MATLAB bug because I am able to read them using python.
2. On another few images (also ~10 of them), the function `intrinsic_decomp` which call `getGridLLEMatrix` through a segmentation fault. And I think this is related to what you are saying of Mex + GCC + Ubuntu not being the exact same versions as the ones originally used.

Since it is only ~20 images that are not working, I think for the dataset it might be ok, but I am concerned that because of the different Mex compilations I have that the `ConvertRGBD.m` script may be giving different outputs as yours.

If it is not too much trouble, would you be able to share 5-10 images of the output of `ConvertRGBD.m` so I can compare them with my own output? That way I can make sure that at least the processed images I have are correct.

Thanks!
Felipe

**Comment by JiayongO-O** [comment]
Hi Felipe,

I also have some problems in reading data with Matlab in Ubuntu. And the Matlab in Ubuntu is not always stable. In addition, mex files would also bring crashes. 

Yes, I have sent the files to your email address, please check it. Hope it helps.

Thanks.
Jiayong

**Comment by Vishal-S-P** [comment]
![image](https://user-images.githubusercontent.com/86377748/161402825-57c4623f-1202-4baa-89c8-d0d08d421a2c.png)
Hi Jiayong,
I keep getting errors when I run convertRGBD.m. Did you face any such issue??

**Comment by felipegb94** [comment]
@Vishal-S-P were you able to re-compile the Mex files for your specific machine? If you have not done that, you may need to do it. I posted here what I had to do to get it to work on my machine: [https://github.com/JiayongO-O/PENonLocal/issues/4](https://github.com/JiayongO-O/PENonLocal/issues/4)

Also, like I mention above. In my setup a few of the images (~30 of them) gave a segfault. There is also a few scenes `living_room_0023a` and `living_room_0024a` that have no files in them, which if I recall correctly made the code crash. 

Despite not being able to simulate results for a few images, overall, I was able to get ~13500 instances which was comparable to what Jiayong uses in the paper and enough to re-train the models here.

**Comment by Vishal-S-P** [comment]
Hi Felipe,
Thank You for your response. Actually, I am not able to find libbann.so.0. How do I install this? Does recompiling mex files for my setup resolve this issue?

**Comment by felipegb94** [comment]
Before re-compiling the Mex files I had to install the following:

* `OpenCV 3.4.13` from source. I had to do this because Ubuntu 20.04 will install OpenCV 4+ by default which does not include the deprecated OpenCV 1. This is needed for the `intrinsic_textures` library
  * I followed this tutorial: `https://docs.opencv.org/3.4.13/d7/d9f/tutorial_linux_install.html`
* `libann`: Simply ran `sudo apt install libann-dev`
* `libfreenect`: This has its own pre-requisites so make sure to follow the [install  instructions]([Ubuntu instruction here](https://github.com/OpenKinect/libfreenect)). For Ubuntu I was able to simply install it using the package manager `apt` (after installing the pre-requisites).

**Comment by JiayongO-O** [comment]
Hi guys, isolated by the Covid, I cannot get access to the repo during the past days. Fortunately, it is getting better! Based on the discussion above, I hope the problems in reading data have been addressed. Yeah, I also encountered some problems in reading some data with the functions provided in the [NYU2 dataset](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html). So my suggestions are: try to install the opencv=3.4.7, libann=1.1.2; if it is possible, try to generate the data under windows, which is much stable than that in Ubuntu. Hope it helps. Thanks.

**Comment by Vishal-S-P** [comment]
Hi @felipegb94 ,
Is it possible to share the final dataset that you generated??

Thank You,
Vishal

**Comment by felipegb94** [comment]
Hi @Vishal-S-P ,

I might be able to share the dataset within the next week. I need to upload it to google drive and then I can send you a link where you can download it from.

By the way, the test data simulated with the Middlebury dataset and also some real test data can be downloaded directly from [Lindell et al., SIGGRAPH 2018 project page](https://www.computationalimaging.org/publications/single-photon-3d-imaging-with-deep-sensor-fusion/)

Felipe

**Comment by Vishal-S-P** [comment]
@felipegb94  Thank you so much.

**Comment by felipegb94** [comment]
@Vishal-S-P I am still uploading the dataset, but you can start downloading the dataset `.zip` that has finished uploading from this google drive link: [https://drive.google.com/drive/folders/1dVcJWHmzqBrc4GsrRiuTiXZgohFStTT5?usp=sharing](https://drive.google.com/drive/folders/1dVcJWHmzqBrc4GsrRiuTiXZgohFStTT5?usp=sharing)

It should be another 2-3 days until the data is fully uploaded.

The `processed` folder contents will go under `data_gener/TrainData/processed` if you are using Jiaoyong's implementation. 

I also simulated the Middlebury test dataset. [You can download it from here](https://drive.google.com/drive/folders/15D1iK8fBniiXLd6o4r_SpblPNRn_MZ-k?usp=sharing). 

Hope this helps,
Felipe

**Comment by Vishal-S-P** [comment]
Hi @felipegb94, Can you confirm the number of zip files that you have uploaded, and are your done uploading??

Thank You,
vishal

**Comment by Vishal-S-P** [comment]
@felipegb94 Thank you for uploading and confirming :-)
