### ISSUE TITLE
Bug in testing code - Incorrect reshape of input spad measurements

### ISSUE THREAD

**Issue by felipegb94** [JiayongO-O/PENonLocal#6]
Hi,

With some minor modifications, I was able to generate the training dataset and train a model with the default training parameters provided. 

However, when I ran the test code I got [the following results on the test dataset](https://www.dropbox.com/s/hmi1si1li8i242i/old_test_load.png?dl=0)

At first I thought the training procedure didn't work, but when I would input train images in the test code, they would work, but appear transposed. So I figured it was a reshape issue. After some playing around I found the error was in `Fn_test.py` in how `M_mea` is reshaped. 

Here is a short snippet of how it is currently done (this produces the above wrong result): 

```
        M_mea = np.asarray(M_mea).astype(np.float32).reshape([1, 1, h, w, -1])
        M_mea = torch.from_numpy(np.transpose(M_mea, (0, 1, 4, 2, 3))).type(dtype)
        M_mea_re, dep_re = model(M_mea)
``` 

And finally, here is my modified snipped [which produces a reasonable result](https://www.dropbox.com/s/clh9rt6y661aasu/new_test_load.png?dl=0)

```
        M_mea = np.asarray(M_mea).astype(np.float32).reshape([1, 1, w, h, -1])
        M_mea = torch.from_numpy(np.transpose(M_mea, (0, 1, 4, 2, 3))).type(dtype)
        M_mea_re, dep_re = model(M_mea)
        dist = dep_re.data.cpu().numpy()[0, 0, :, :] * Tp * C / 2
        dist = dist.transpose()
``` 

Note that I swapped `w` with `h` in the first line, and then I had to transpose the recovered depths. The above change solved the issue, however, I suspect that the original dimension mismatch between train and test may come from a difference in the `SimualateTestMeasurements.m` and the `SimulateTrainMeasurements.m` scripts. So a cleaner solution may be to edit those scripts.

**Comment by JiayongO-O** [comment]
Hi Felipe, I'm back from the Covid isolation :-). I notice your problem, so I generate the data and put it to the model. But I have not seen the dimension transpose. So I am suspecting that there are some differences possiblely in Matlab saving files (for example, saving with .mat v7.3 or v7); the sparse.csc_matrix in scipy may also raise dimension transpose. You can change the dimension. And I will add comment on test data generation and test code to remind others. Thanks.
